#pragma once

typedef struct _S_PT_BUY_COINS
{
	INT USER_ID;
	CHAR PASSWORD[32];
	INT PACKET_LEVEL;
	INT DIAMONDS;
	INT COINS;
} S_PT_BUY_COINS;

typedef struct _S_PT_BUY_COINS_SUCC_U
{
	INT PACKET_LEVEL;
	INT DIAMONDS;
	INT COINS;
} S_PT_BUY_COINS_SUCC_U;

typedef struct _S_PT_BUY_COINS_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_BUY_COINS_FAIL_U;

typedef struct _S_PT_BUY_DIAMONDS
{
	INT USER_ID;
	CHAR PASSWORD[32];
	INT PACKET_LEVEL;
	INT DIAMONDS;
} S_PT_BUY_DIAMONDS;

typedef struct _S_PT_BUY_DIAMONDS_SUCC_U
{
	INT PACKET_LEVEL;
	INT DIAMONDS;
} S_PT_BUY_DIAMONDS_SUCC_U;

typedef struct _S_PT_BUY_DIAMONDS_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_BUY_DIAMONDS_FAIL_U;

typedef struct _S_PT_BUY_CARDS
{
	INT USER_ID;
	CHAR PASSWORD[32];
	INT COINS;
	INT CARD_TYPE;
	CHAR CARD_NAME[32];
	INT CARD_NUM;
} S_PT_BUY_CARDS;

typedef struct _S_PT_BUY_CARDS_SUCC_U
{
	INT COINS;
	INT CARD_TYPE;
	CHAR CARD_NAME[32];
	INT CARD_NUM;
} S_PT_BUY_CARDS_SUCC_U;

typedef struct _S_PT_BUY_CARDS_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_BUY_CARDS_FAIL_U;

typedef struct _S_PT_OPEN_SUPPLY_CHEST
{
	INT USER_ID;
	CHAR PASSWORD[32];
	INT LEVEL;
	INT CHEST_TYPE;
	CHAR CARD_NAME[32];
	INT COINS;
	INT DIAMONDS;
} S_PT_OPEN_SUPPLY_CHEST;

typedef struct _S_PT_OPEN_SUPPLY_CHEST_SUCC_U
{
	INT CHEST_TYPE;
	INT CHEST_NUM;
	INT STAR_NUM;
	INT COINS;
	INT DIAMONDS;
	INT CARD_1_TYPE;
	INT CARD_2_TYPE;
	INT CARD_3_TYPE;
	INT CARD_4_TYPE;
	INT CARD_5_TYPE;
	INT CARD_6_TYPE;
	INT CARD_7_TYPE;
	INT CARD_8_TYPE;
	INT CARD_1_LEVEL;
	INT CARD_2_LEVEL;
	INT CARD_3_LEVEL;
	INT CARD_4_LEVEL;
	INT CARD_5_LEVEL;
	INT CARD_6_LEVEL;
	INT CARD_7_LEVEL;
	INT CARD_8_LEVEL;
	INT CARD_1_NUM;
	INT CARD_2_NUM;
	INT CARD_3_NUM;
	INT CARD_4_NUM;
	INT CARD_5_NUM;
	INT CARD_6_NUM;
	INT CARD_7_NUM;
	INT CARD_8_NUM;
} S_PT_OPEN_SUPPLY_CHEST_SUCC_U;

typedef struct _S_PT_OPEN_SUPPLY_CHEST_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_OPEN_SUPPLY_CHEST_FAIL_U;

typedef struct _S_PT_LOAD_CARDS_ON_SALE
{
	INT USER_LEVEL;
} S_PT_LOAD_CARDS_ON_SALE;

typedef struct _S_PT_LOAD_CARDS_ON_SALE_SUCC_U
{
	INT KINDS_OF_CARDS_ON_SALE;
	INT CARD_1;
	INT CARD_1_COST;
	INT CARD_2;
	INT CARD_2_COST;
	INT CARD_3;
	INT CARD_3_COST;
	INT CARD_4;
	INT CARD_4_COST;
	INT CARD_5;
	INT CARD_5_COST;
	INT CARD_6;
	INT CARD_6_COST;
	INT CARD_7;
	INT CARD_7_COST;
	INT CARD_8;
	INT CARD_8_COST;
	INT CARD_9;
	INT CARD_9_COST;
} S_PT_LOAD_CARDS_ON_SALE_SUCC_U;

typedef struct _S_PT_LOAD_CARDS_ON_SALE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_LOAD_CARDS_ON_SALE_FAIL_U;

typedef struct _S_PT_UPGRADE_CARD
{
	INT CARD_TYPE;
	INT CARD_LEVEL;
} S_PT_UPGRADE_CARD;

typedef struct _S_PT_UPGRADE_CARD_SUCC_U
{
	INT CARD_TYPE;
	INT CARD_LEVEL;
	INT CARD_UPGRADE_COST;
	INT CARD_NUM_UPGRADE_NEED;
} S_PT_UPGRADE_CARD_SUCC_U;

typedef struct _S_PT_UPGRADE_CARD_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_UPGRADE_CARD_FAIL_U;

typedef struct _S_PT_ACQUIRE_CHEST
{
	INT CHEST_TYPE;
} S_PT_ACQUIRE_CHEST;

typedef struct _S_PT_ACQUIRE_CHEST_SUCC_U
{
	INT CHEST_TYPE;
	INT64 ACQUIRE_TIME;
	INT64 UNLOCK_TIME;
} S_PT_ACQUIRE_CHEST_SUCC_U;

typedef struct _S_PT_ACQUIRE_CHEST_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ACQUIRE_CHEST_FAIL_U;

