#pragma once
#include <windows.h>

typedef enum USER_PROTOCOL
{
	USER_PT_VERSION	= 0x1000000,

	PT_VISITOR_REGIST,
	/*
	*/
	PT_VISITOR_REGIST_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_VISITOR_REGIST_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_USER_NAME_REGIST,
	/*
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	*/
	PT_USER_NAME_REGIST_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_USER_NAME_REGIST_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_BIND_ACCOUNT_REGIST,
	/*
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	*/
	PT_BIND_ACCOUNT_REGIST_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_BIND_ACCOUNT_REGIST_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_CELLPHONE_NO_REGIST,
	/*
	CHAR						:		CELLPHONE_NO[32]
	INT							:		CONFIG_CODE
	*/
	PT_CELLPHONE_NO_REGIST_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_CELLPHONE_NO_REGIST_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_USER_NAME_LOGIN,
	/*
	CHAR						:		USER_NAME[32]
	CHAR						:		PASSWORD[32]						
	*/
	PT_USER_NAME_LOGIN_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_USER_NAME_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_BIND_ACCOUNT_LOGIN,
	/*
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	*/
	PT_BIND_ACCOUNT_LOGIN_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_BIND_ACCOUNT_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_CELLPHONE_NO_LOGIN,
	/*
	CHAR						:		CELLPHONE_NO[32]
	INT							:		CONFIG_CODE
	*/
	PT_CELLPHONE_NO_LOGIN_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_CELLPHONE_NO_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_VISITOR_DEFAULT_LOGIN,
	/*
	INT							:		USER_ID
	CHAR						:		PASSWORD[32]
	*/
	PT_VISITOR_DEFAULT_LOGIN_SUCC_U,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	CHAR						:		PASSWORD[32]
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	CHAR						:		CELLPHONE_NO[32]
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_VISITOR_DEFAULT_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_USER_NAME_DEFAULT_LOGIN,
	/*
	INT							:		USER_ID
	CHAR						:		USER_NAME[32]
	CHAR						:		PASSWORD[32]
	*/
	PT_USER_NAME_DEFAULT_LOGIN_SUCC_U,
	/*
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_USER_NAME_DEFAULT_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_BIND_ACCOUNT_DEFAULT_LOGIN,
	/*
	INT							:		USER_ID
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	*/
	PT_BIND_ACCOUNT_DEFAULT_LOGIN_SUCC_U,
	/*
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_BIND_ACCOUNT_DEFAULT_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_CELLPHONE_NO_DEFAULT_LOGIN,
	/*
	INT							:		USER_ID
	CHAR						:		CELLPHONE_NO[32]
	INT							:		CONFIG_CODE
	*/
	PT_CELLPHONE_NO_DEFALUT_LOGIN_SUCC_U,
	/*
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	DWORD_PTR		:		SESSION_ID
	INT							:		NUM_OF_JUNIOR_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_PLANE_CARD
	INT							:		NUM_OF_SENIOR_PLANE_CARD
	INT							:		NUM_OF_JUNIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_MIDDLE_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_STEALTH_PLANE_CARD
	INT							:		NUM_OF_SENIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_ANTI_STEALTH_RADAR_CARD
	INT							:		NUM_OF_SENIOR_MISSILE_CARD
	INT							:		NUM_OF_MIDDLE_MISSILE_CARD
	INT							:		NUM_OF_JUNIOR_MISSILE_CARD
	INT							:		NUM_OF_SENIOR_RADAR_CARD
	INT							:		NUM_OF_MIDDLE_RADAR_CARD
	INT							:		NUM_OF_JUNIOR_RADAR_CARD
	INT							:		NUM_OF_SENIOR_CANNONBALL_CARD
	INT							:		NUM_OF_MIDDLE_CANNONBALL_CARD
	INT							:		NUM_OF_JUNIOR_CANNONBALL_CARD
	INT							:		LEVEL_JUNIOR_PLANE
	INT							:		LEVEL_MIDDLE_PLANE
	INT							:		LEVEL_SENIOR_PLANE
	INT							:		LEVEL_JUNIOR_STEALTH_PLANE
	INT							:		LEVEL_MIDDLE_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_STEALTH_PLANE
	INT							:		LEVEL_SENIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_MIDDLE_ANTI_STEALTH_RADAR
	INT							:		LEVEL_JUNIOR_ANTI_STEALTH_RADAR
	INT							:		LEVEL_SENIOR_MISSILE
	INT							:		LEVEL_MIDDLE_MISSILE
	INT							:		LEVEL_JUNIOR_MISSILE
	INT							:		LEVEL_SENIOR_RADAR
	INT							:		LEVEL_MIDDLE_RADAR
	INT							:		LEVEL_JUNIOR_RADAR
	INT							:		LEVEL_SENIOR_CANNONBALL
	INT							:		LEVEL_MIDDLE_CANNONBALL
	INT							:		LEVEL_JUNIOR_CANNONBALL
	INT							:		STAR_NUM
	INT							:		WIN_REWARDS_1_NUM
	INT							:		WIN_REWARDS_2_NUM
	INT							:		WIN_REWARDS_3_NUM
	INT							:		WIN_REWARDS_4_NUM
	INT							:		WIN_REWARDS_5_NUM
	INT							:		STAR_REWARDS_NUM
	INT							:		FREE_REWARDS_NUM
	INT64							:		WIN_REWARDS_1_UNLOCK_TIME
	INT64							:		WIN_REWARDS_2_UNLOCK_TIME
	INT64							:		WIN_REWARDS_3_UNLOCK_TIME
	INT64							:		WIN_REWARDS_4_UNLOCK_TIME
	INT64							:		WIN_REWARDS_5_UNLOCK_TIME
	INT64							:		LAST_STAR_REWARDS_ACQUIRE_TIME
	INT64							:		LAST_FREE_REWARDS_ACQUIRE_TIME
	*/
	PT_CELLPHONE_NO_DEFAULT_LOGIN_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_ADD_NICKNAME,
	/*
	INT							:		USER_ID
	CHAR						:		NICKNAME[32]
	*/
	PT_ADD_NICKNAME_SUCC_U,
	/*
	CHAR						:		NICKNAME[32]
	*/
	PT_ADD_NICKNAME_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_ADD_BIND_ACCOUNT,
	/*
	INT							:		USER_ID
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	*/
	PT_ADD_BIND_ACCOUNT_SUCC_U,
	/*
	CHAR						:		BIND_ACCOUNT_TYPE[32]
	CHAR						:		BIND_ACCOUNT[32]
	*/
	PT_ADD_BIND_ACCOUNT_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_ADD_CELLPHONE_NO,
	/*
	INT							:		USER_ID
	CHAR						:		CELLPHONE_NO[32]
	INT							:		CONFIG_CODE
	*/
	PT_ADD_CELLPHONE_NO_SUCC_U,
	/*
	CHAR						:		CELLPHONE_NO[32]
	*/
	PT_ADD_CELLPHONE_NO_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_UPDATE_PASSWORD,
	/*
	INT							:		USER_ID
	CHAR						:		OLD_PASSWORD[32]
	CHAR						:		NEW_PASSWORD[32]
	*/
	PT_UPDATE_PASSWORD_SUCC_U,
	/*
	CHAR						:		NEW_PASSWORD[32]
	*/
	PT_UPDATE_PASSWORD_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_UPDATE_NICKNAME,
	/*
	INT							:		USER_ID
	CHAR						:		OLD_NICKNAME[32]
	CHAR						:		NEW_NICKNAME[32]
	*/
	PT_UPDATE_NICKNAME_SUCC_U,
	/*
	CHAR						:		NEW_NICKNAME[32]
	*/
	PT_UPDATE_NICKNAME_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_UPDATE_CELLPHONE_NO,
	/*
	INT							:		USER_ID
	CHAR						:		NEW_CELLPHONE_NO[32]
	INT							:		CONFIG_CODE
	*/
	PT_UPDATE_CELLPHONE_NO_SUCC_U,
	/*
	CHAR						:		NEW_CELLPHONE_NO[32]
	*/
	PT_UPDATE_CELLPHONE_NO_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	PT_UPDATE_RECORD,
	/*
	INT							:		USER_ID
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	*/
	PT_UPDATE_RECORD_SUCC_U,
	/*
	INT							:		INTEGRAL_POINTS
	INT							:		LEVEL
	INT							:		DIAMONDS
	INT							:		COINS
	INT							:		WIN_TIMES
	INT							:		BATTLE_TIMES
	FLOAT					:		WIN_RATE
	INT							:		SHOT_DOWN_PLANES
	INT							:		SHOT_DOWN_JUNIOR_PLANES
	INT							:		SHOT_DOWN_MIDDLE_PLANES
	INT							:		SHOT_DOWN_SENIOR_PLANES
	*/
	PT_UPDATE_RECORD_FAIL_U,
	/*
	DWORD					:		ERROR_CODE
	*/
	USER_PT_END
};